AddPackage audacious # Simple music player
AddPackage audacity # Sound editor
AddPackage baka-mplayer
AddPackage chromium
AddPackage deepin-calculator
AddPackage deluge
AddPackage deluge-gtk
AddPackage discord
AddPackage dolphin
AddPackage dolphin-plugins
AddPackage filezilla
AddPackage firefox
AddPackage flatpak
AddPackage gimp
AddPackage gparted
AddPackage handbrake
AddPackage inkscape
AddPackage kakasi
AddPackage krenamekf5
AddPackage leafpad
AddPackage libreoffice-fresh
AddPackage lutris
AddPackage mpv
AddPackage navidrome
AddPackage obsidian
AddPackage openrgb
AddPackage openshot
AddPackage qbittorrent
AddPackage rmlint-shredder
AddPackage steam
AddPackage telegram-desktop
AddPackage torbrowser-launcher
AddPackage virtualbox
AddPackage virtualbox-guest-iso
AddPackage virtualbox-guest-utils
AddPackage vlc
